name: Detect changes in packages
on:
  workflow_call:
    inputs:
      event:
        description: 'Trigger event of the calling workflow'
        required: true
        type: string
    outputs:
      packages:
        description: 'Names of the changed packages'
        value: ${{ jobs.changes.outputs.packages }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        if: ${{ inputs.event == 'push' }}
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Get changed packages
        uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        id: filter
        with:
          filters: |
            dmenu-royarg-git: 'dmenu-royarg-git/**'
            dwm-royarg-git: 'dwm-royarg-git/**'
            dwmblocks-royarg-git: 'dwmblocks-royarg-git/**'
            lf-royarg-bin: 'lf-royarg-bin/**'
            slock-royarg-git: 'slock-royarg-git/**'
            st-royarg-git: 'st-royarg-git/**'

