name: Detect changes in packages
on:
  workflow_call:
    inputs:
      event:
        description: 'Trigger event of the calling workflow'
        required: true
        type: string
    outputs:
      packages:
        description: 'Names of the changed packages'
        value: ${{ jobs.changes.outputs.packages }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        if: ${{ inputs.event == 'push' }}
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Get changed packages
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            dmenu-royarg-git: 'dmenu-royarg-git/**'
            dwm-royarg-git: 'dwm-royarg-git/**'
            dwmblocks-royarg-git: 'dwmblocks-royarg-git/**'
            lf-royarg-bin: 'lf-royarg-bin/**'
            slock-royarg-git: 'slock-royarg-git/**'
            st-royarg-git: 'st-royarg-git/**'
            xivr: 'xivr/**'

