name: Package upload
on:
  push:
    paths:
      - '**/PKGBUILD'
      - '**/.SRCINFO'
    branches:
      - master

jobs:
  changes:
    uses: ./.github/workflows/detect-changes.yaml
    with:
      event: ${{ github.event_name }}

  package-upload:
    needs: changes
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ matrix.package }}
    steps:
      - name: Checkout build files
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - name: Update container image
        run: pacman -Syu --noconfirm
      - name: Install git and wget
        run: pacman -S --needed --noconfirm git wget
      - name: Enable "royarg-repo" repository
        uses: ./.github/actions/enable-royarg-repo
      - name: Import GPG key for signing package
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Modify permissions for build directories
        uses: ./.github/actions/perm-build-dirs
      - name: Add packager information
        run: |
          cat << END >> /etc/makepkg.conf
          PACKAGER="Anurag Roy <anuragr9847@gmail.com>"
          END
      - name: Disable building debug packages
        run: sed -i '/^OPTIONS/ s/ debug/ !debug/' /etc/makepkg.conf
      - name: Build package
        run: sudo -u nobody makepkg --syncdeps --noconfirm
      - name: Sign packages
        run: |
          for pkgfile in $(sudo -u nobody makepkg --packagelist); do
            gpg --detach-sign --pinentry-mode loopback --passphrase --passphrase-fd 0 --output "${pkgfile}.sig" --sign "${pkgfile}" <<< "${{ secrets.GPG_PASSPHRASE }}"
          done
      - name: Checkout package repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          repository: 'royarg02/royarg-repo'
          path: 'royarg-repo'
          token: ${{ secrets.GH_PAT }}
      - name: Move built files to package repository
        run: |
          for pkgfile in $(sudo -u nobody makepkg --packagelist); do
            mv "${pkgfile}"{,.sig} ${GITHUB_WORKSPACE}/royarg-repo/static/os/x86_64/
          done
      - name: Push new files to package repository
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          message: 'Package update from https://github.com/${{ github.repository }}/commit/${{ github.sha }}'
          cwd: 'royarg-repo'
          default_author: github_actions

